### ISSUE TITLE
can't add created object to DBSet

### ISSUE THREAD

**Issue by nerumo** [dbroudy/LazyEntityGraph#1]
Since the created POCO objects are of a castle proxy type I can't add them to a DBSet since the type is not known to EF. EF only knows his own proxy type that is emitted at runtime.
Is there a way to work around that problem? Or would the solution be to let the castle proxy inherit from the EF proxy type instead of the POCO type?

**Comment by dbroudy** [comment]
Hi @nerumo, I just took over the maintenance of LazyEntityGraph and see this question has been outstanding for a while.

I would suggest that you should not add an AutoFixture created object to a real DbSet. Instead you should create a mock DbSet / DbContext for your tests. The mock implementation shouldn't have any issue working with the castle proxy since it's a subclass of your entity type.

This project is only one part of creating tests for an Entity Framework based code base. Personally, I use this in combination with Moq to create a mock DbContext and [EntityFramework.Testing.Moq](https://github.com/scott-xu/EntityFramework.Testing) to setup data in my DbSets. I plan to do a post at some point in the future detailing the complete setup.

**Comment by nerumo** [comment]
tnx, good enough
